### ISSUE TITLE
Expand ambassador menu on first load, store menu state

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/extension#134]
To increase awareness of the extension and the ambassador information within, on first load of the extension for a user we should consider defaulting to the ambassador menu being shown.

We could then write to local storage what menu the user has opened, so if they close the menu and reload the page, it won't re-open on load. Similarly though, if they leave it open and reload the page, we'll re-open it on load.

**Comment by svandajan** [comment]
> (...) We could then write to **local storage** what menu the user has opened...

**Local storage** in this case means browser storage, or some Twitch storage attached to user's account? If it is the first case, it will of course reopen when user uses new browser (eg. from laptop). Maybe instead of the classic _full overlay mode_ (like when triggered by mods), there should be just _smaller, easily dismissed pop-up_? I am thinking something of some bar/window on top of the screen (so it will not cover half the stream), with _more "aggressive" coloring_ - so people will read it but it wouldn't become a bother if they see it again when they eg. change device.

**Comment by MattIPv4** [comment]
This would indeed be browser storage, not anything stored with Twitch -- so it'd show on first-load in any new browser/device.

To be clear, it won't be the full card pop up like you'd get when a mod triggers the overlay, it'll just be the ambassador menu, which is relatively unobtrusive and is a single click to dismiss. The idea is just to raise awareness that information about the ambassadors is in the extension under the ambassadors button, not to try and show a random ambassador in load.

**Comment by MattIPv4** [comment]
Hey @trimbe, I see you had some commits referencing this issue that appear to be a great approach to this -- are you intending to open a PR for that?

**Comment by trimbe** [comment]
Oh, yes, kinda forgot about that.
