### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by abdullahmorrison** [alveusgg/extension#43]
track usage

**Comment by abdullahmorrison** [comment]
Maya values impact so if we can find ways to track how the extension has resulted in someone learning more and contributing to conservation that would be great.

Things that would be useful to track:
- [ ] If a user reads the ambassador cards after a chat command is initiated (if they hover their cursor over the cards maybe)
- [ ] If a user looks at other ambassadors after a chat command
- [ ] How many people block the pop ups

**Comment by MattIPv4** [comment]
I'm going to close this out, as running GA would require getting explicit consent from users most likely, and I think that'd drastically impact usage of the extension. This feels somewhat like collecting data for the sake of collecting data rather than to answer as specific question we have to solve a problem / implement a new feature in the extension.

Definitely open to re-considering some form of properly anonymous tracking that doesn't require consent if we feel there is a need to track interactions/clicks on a specific part of the extension for some reason.

Also worth noting that Twitch does give us some basic analytics on their end for the extension (interactions + viewers).
