### ISSUE TITLE
Design alveus intro for the panel view

### ISSUE THREAD

**Issue by abdullahmorrison** [alveusgg/extension#53]
Design the wireframe to incorporate the alveus intro into the panel view.
- Probably needs some nav bar at the bottom
- Intro probably needs to be a new page
  - Could also be a popup similar to the card pop up

**Comment by kasaharas** [comment]
Hello! Is this issue still open to pick up? Is it still valid / desired?

**Comment by MattIPv4** [comment]
Yes, I believe so. I think it'd be useful for the extension in its panel form to have some sort of minimal "info" button or similar to trigger showing information similar to what is show in the welcome card of the overlay.

**Comment by kasaharas** [comment]
Thanks Matt! Do we want the same exact content from the welcome overlay card or should the panel version be a separate component altogether? In the case of the same content, I was considering pulling the `Welcome` component into a shared component so that both the overlay and panel could use it. If we think the content would diverge, then I would create a separate component. Appreciate any advice 🙏

**Comment by MattIPv4** [comment]
Sharing the content/component seems fine, assuming the layout is responsive enough to work in both situations :)
